// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/HarmonyCandies/permission_handler_ohos
// **************************************************************************
// https://gitee.com/openharmony/docs/blob/OpenHarmony-4.1-Beta1/zh-cn/application-dev/security/AccessToken/permissions-for-all.md
// ignore_for_file: constant_identifier_names,slash_for_doc_comments

/// The Permissions of OpenHarmony
/// total: 45
enum PermissionOhos {
  /// ohos.permission.USE_BLUETOOTH
  ///
  /// 允许应用查看蓝牙的配置。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  use_bluetooth(
    name: 'ohos.permission.USE_BLUETOOTH',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.GET_BUNDLE_INFO
  ///
  /// 允许查询应用的基本信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  get_bundle_info(
    name: 'ohos.permission.GET_BUNDLE_INFO',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.PREPARE_APP_TERMINATE
  ///
  /// 允许应用关闭前执行自定义的预关闭动作。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：10

  prepare_app_terminate(
    name: 'ohos.permission.PREPARE_APP_TERMINATE',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 10,
  ),

  /// ohos.permission.PRINT
  ///
  /// 允许应用获取打印框架的能力。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：10

  print(
    name: 'ohos.permission.PRINT',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 10,
  ),

  /// ohos.permission.DISCOVER_BLUETOOTH
  ///
  /// 允许应用配置本地蓝牙，查找远端设备且与之配对连接。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  discover_bluetooth(
    name: 'ohos.permission.DISCOVER_BLUETOOTH',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.ACCELEROMETER
  ///
  /// 允许应用读取加速度传感器的数据。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  accelerometer(
    name: 'ohos.permission.ACCELEROMETER',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.ACCESS_BIOMETRIC
  ///
  /// 允许应用使用生物特征识别能力进行身份认证。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：6

  access_biometric(
    name: 'ohos.permission.ACCESS_BIOMETRIC',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 6,
  ),

  /// ohos.permission.ACCESS_NOTIFICATION_POLICY
  ///
  /// 在本设备上允许应用访问通知策略。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：7

  access_notification_policy(
    name: 'ohos.permission.ACCESS_NOTIFICATION_POLICY',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: false,
    startVersion: 7,
  ),

  /// ohos.permission.GET_NETWORK_INFO
  ///
  /// 允许应用获取数据网络信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  get_network_info(
    name: 'ohos.permission.GET_NETWORK_INFO',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.GET_WIFI_INFO
  ///
  /// 允许应用获取Wi-Fi信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  get_wifi_info(
    name: 'ohos.permission.GET_WIFI_INFO',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.GYROSCOPE
  ///
  /// 允许应用读取陀螺仪传感器的数据。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  gyroscope(
    name: 'ohos.permission.GYROSCOPE',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.INTERNET
  ///
  /// 允许使用Internet网络。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：9

  internet(
    name: 'ohos.permission.INTERNET',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 9,
  ),

  /// ohos.permission.KEEP_BACKGROUND_RUNNING
  ///
  /// 允许Service Ability在后台持续运行。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  keep_background_running(
    name: 'ohos.permission.KEEP_BACKGROUND_RUNNING',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.NFC_CARD_EMULATION
  ///
  /// 允许应用实现卡模拟功能。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：8

  nfc_card_emulation(
    name: 'ohos.permission.NFC_CARD_EMULATION',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: false,
    startVersion: 8,
  ),

  /// ohos.permission.NFC_TAG
  ///
  /// 允许应用读写Tag卡片。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：7

  nfc_tag(
    name: 'ohos.permission.NFC_TAG',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: false,
    startVersion: 7,
  ),

  /// ohos.permission.PRIVACY_WINDOW
  ///
  /// 允许应用将窗口设置为隐私窗口，禁止截屏录屏
  ///
  /// 权限级别：system_basic
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：9

  privacy_window(
    name: 'ohos.permission.PRIVACY_WINDOW',
    permissionLevel: 'system_basic',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 9,
  ),

  /// ohos.permission.PUBLISH_AGENT_REMINDER
  ///
  /// 允许该应用使用后台代理提醒。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  publish_agent_reminder(
    name: 'ohos.permission.PUBLISH_AGENT_REMINDER',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.SET_NETWORK_INFO
  ///
  /// 允许应用配置数据网络。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  set_network_info(
    name: 'ohos.permission.SET_NETWORK_INFO',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.SET_WIFI_INFO
  ///
  /// 允许应用配置Wi-Fi设备。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  set_wifi_info(
    name: 'ohos.permission.SET_WIFI_INFO',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.VIBRATE
  ///
  /// 允许应用控制马达振动。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  vibrate(
    name: 'ohos.permission.VIBRATE',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.CLEAN_BACKGROUND_PROCESSES
  ///
  /// 允许应用根据包名清理相关后台进程。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  clean_background_processes(
    name: 'ohos.permission.CLEAN_BACKGROUND_PROCESSES',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.COMMONEVENT_STICKY
  ///
  /// 允许应用发布粘性公共事件。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  commonevent_sticky(
    name: 'ohos.permission.COMMONEVENT_STICKY',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.MODIFY_AUDIO_SETTINGS
  ///
  /// 允许应用修改音频设置。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  modify_audio_settings(
    name: 'ohos.permission.MODIFY_AUDIO_SETTINGS',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.RUNNING_LOCK
  ///
  /// 允许应用获取运行锁，保证应用在后台的持续运行。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  running_lock(
    name: 'ohos.permission.RUNNING_LOCK',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.SET_WALLPAPER
  ///
  /// 允许应用设置壁纸。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  set_wallpaper(
    name: 'ohos.permission.SET_WALLPAPER',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.ACCESS_CERT_MANAGER
  ///
  /// 允许应用进行查询证书及私有凭据等操作。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：9

  access_cert_manager(
    name: 'ohos.permission.ACCESS_CERT_MANAGER',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: false,
    startVersion: 9,
  ),

  /// ohos.permission.hsdr.HSDR_ACCESS
  ///
  /// 允许应用访问安全检测与响应框架。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：10

  hsdr_access(
    name: 'ohos.permission.hsdr.HSDR_ACCESS',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: false,
    startVersion: 10,
  ),

  /// ohos.permission.RUN_DYN_CODE
  ///
  /// 允许应用运行动态代码。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：11

  run_dyn_code(
    name: 'ohos.permission.RUN_DYN_CODE',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: false,
    startVersion: 11,
  ),

  /// ohos.permission.READ_CLOUD_SYNC_CONFIG
  ///
  /// 允许接入云空间的应用查询应用云同步相关配置信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：11

  read_cloud_sync_config(
    name: 'ohos.permission.READ_CLOUD_SYNC_CONFIG',
    permissionLevel: 'normal',
    grantType: 'system_grant',
    aclEnabled: true,
    startVersion: 11,
  ),

  /// ohos.permission.STORE_PERSISTENT_DATA
  ///
  /// 允许应用存储持久化的数据，该数据直到设备恢复出厂设置或重装系统才会被清除。
  ///
  /// 权限级别: normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能: false
  ///
  /// 起始版本: 11
  ///
  /// ohos.permission.ACCESS_EXTENSIONAL_DEVICE_DRIVER
  /// 允许应用使用外接设备增强功能。
  ///
  /// 权限级别: normal
  ///
  /// 授权方式：system_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：11

  store_persistent_data(
    name: 'ohos.permission.STORE_PERSISTENT_DATA',
    permissionLevel: '',
    grantType: 'system_grant',
    aclEnabled: false,
    startVersion: 11,
  ),

  /// ohos.permission.ACCESS_BLUETOOTH
  ///
  /// 允许应用接入蓝牙并使用蓝牙能力，例如配对、连接外围设备等。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：10

  access_bluetooth(
    name: 'ohos.permission.ACCESS_BLUETOOTH',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: false,
    startVersion: 10,
  ),

  /// ohos.permission.MEDIA_LOCATION
  ///
  /// 允许应用访问用户媒体文件中的地理位置信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  media_location(
    name: 'ohos.permission.MEDIA_LOCATION',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.APP_TRACKING_CONSENT
  ///
  /// 允许应用读取开放匿名设备标识符。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：9

  app_tracking_consent(
    name: 'ohos.permission.APP_TRACKING_CONSENT',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 9,
  ),

  /// ohos.permission.ACTIVITY_MOTION
  ///
  /// 允许应用读取用户的运动状态。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  activity_motion(
    name: 'ohos.permission.ACTIVITY_MOTION',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.CAMERA
  ///
  /// 允许应用使用相机。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：9

  camera(
    name: 'ohos.permission.CAMERA',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 9,
  ),

  /// ohos.permission.DISTRIBUTED_DATASYNC
  ///
  /// 允许不同设备间的数据交换。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  distributed_datasync(
    name: 'ohos.permission.DISTRIBUTED_DATASYNC',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.LOCATION_IN_BACKGROUND
  ///
  /// 允许应用在后台运行时获取设备位置信息。
  ///
  /// 申请条件：需要先申请前台位置权限ohos.permission.LOCATION和ohos.permission.APPROXIMATELY_LOCATION后，才可申请此权限。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：7

  location_in_background(
    name: 'ohos.permission.LOCATION_IN_BACKGROUND',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: false,
    startVersion: 7,
  ),

  /// ohos.permission.LOCATION
  ///
  /// 允许应用获取设备位置信息。
  ///
  /// 申请条件：需要先申请模糊位置权限ohos.permission.APPROXIMATELY_LOCATION，才可申请此权限。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  location(
    name: 'ohos.permission.LOCATION',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.APPROXIMATELY_LOCATION
  ///
  /// 允许应用获取设备模糊位置信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：false
  ///
  /// 起始版本：9

  approximately_location(
    name: 'ohos.permission.APPROXIMATELY_LOCATION',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: false,
    startVersion: 9,
  ),

  /// ohos.permission.MICROPHONE
  ///
  /// 允许应用使用麦克风。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  microphone(
    name: 'ohos.permission.MICROPHONE',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.READ_CALENDAR
  ///
  /// 允许应用读取日历信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  read_calendar(
    name: 'ohos.permission.READ_CALENDAR',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.READ_HEALTH_DATA
  ///
  /// 允许应用读取用户的健康数据。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  read_health_data(
    name: 'ohos.permission.READ_HEALTH_DATA',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.READ_MEDIA
  ///
  /// 允许应用读取用户外部存储中的媒体文件信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  read_media(
    name: 'ohos.permission.READ_MEDIA',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 7,
  ),

  /// ohos.permission.WRITE_CALENDAR
  ///
  /// 允许应用添加、移除或更改日历活动。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：8

  write_calendar(
    name: 'ohos.permission.WRITE_CALENDAR',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 8,
  ),

  /// ohos.permission.WRITE_MEDIA
  ///
  /// 允许应用读写用户外部存储中的媒体文件信息。
  ///
  /// 权限级别：normal
  ///
  /// 授权方式：user_grant
  ///
  /// ACL使能：true
  ///
  /// 起始版本：7

  write_media(
    name: 'ohos.permission.WRITE_MEDIA',
    permissionLevel: 'normal',
    grantType: 'user_grant',
    aclEnabled: true,
    startVersion: 7,
  ),
  ;

  const PermissionOhos({
    required this.name,
    required this.permissionLevel,
    required this.aclEnabled,
    required this.grantType,
    required this.startVersion,
  });

  final String name;
  final String permissionLevel;
  final bool aclEnabled;
  final String grantType;
  final int startVersion;
}
